name: Release

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    if: github.ref_name == 'main' || github.ref_name == 'next'

    needs:
      - lint
      - build
      - test

    uses: ./.github/workflows/publish.yml
    secrets: inherit